package com.bougouri.timetable.business.service.Exception;

public enum ExceptionType {
	LOGIN_ALREADY_EXISTS, TIME_SLOT_OVERLAP, APPOINTMENT_OVERLAP, HOLIDAY_OVERLAP, HOLIDAY_ON_APPOINTMENT, APPOINTMENT_ON_HOLIDAY, MISSING_ENTITY, FUNCTIONAL, TECHNICAL, INVALID_PROPERTY_VALUE
}
