dataSource:
   driver: org.postgresql.Driver
   dialect: org.hibernate.dialect.PostgreSQLDialect
   url: jdbc:postgresql://localhost:5432/bougouri
   user: postgres
   password: YWRtaW4=
   schemaStartegy: create-drop
   showSql: true